@startuml Modelo de clases
!theme mars
class Juego
class Partida{
    codigo
    owner
}
class Usuario{
    nickname
}
class Fase{}
class Inicial{}
class Jugando{}
class Final{}

Inicial -up-|> Fase
Jugando -up-|> Fase
Final -up-|> Fase


Juego --> "1..* usuarios" Usuario
Juego -->"0..* +partidas" Partida
Partida -right->"2" Usuario
Partida --> Fase