@startuml Test Diagram
!theme mars
Node Navegador{
    file indexWeb as "index.html"
    file specRunner as "specRunner.html"
    component cliente


    specRunner ..> cliente

}
Node Server{
file index as "index.js"
file logica as "modelo.js"
component datos

index .down.> logica
logica .down.> datos
}

file Rest
index .. Rest
database BBDD

Navegador --  Server: "HTTP"
BBDD -up- Server: "HTTP"
