@startuml Test Diagram
!theme mars
Node Navegador{
    file indexWeb as "index.html"
    file clienteRest as "clienteRest.js"
    file controlWeb as "controlWeb.js"
    file clienteWS as "clienteWS.js"
    file jquery as "jquery.js"
    file tablero as "tablero.js"

    indexWeb ..> jquery
    indexWeb ..> clienteRest
    indexWeb ..> controlWeb
    indexWeb ..> clienteWS
    indexWeb ..> tablero

}
Node Server{
file index as "index.js"
file logica as "modelo.js"
file servidorWS as "servidorWS.js"
component datos as "Capa Acceso a Datos"
file passportFile as "passport-setup-js"
component passport as "Passport"

index .down.> logica
index ..> servidorWS
servidorWS .> logica
logica .down.> datos
index .down.> passportFile
passportFile .down.> passport
}

component Google
passport .left.> Google

file Rest
index .. Rest
database BBDD

Navegador --  Server: "HTTP"
BBDD -up- Server: "HTTP"
