@startuml Test Diagram
!theme mars
Node Navegador{
    file indexWeb as "index.html"
    file clienteRest as "clienteRest.js"
    file controlWeb as "controlWeb.js"


    indexWeb ..> clienteRest
    indexWeb ..> controlWeb

}
Node Server{
file index as "index.js"
file logica as "modelo.js"
component datos as "Capa Acceso a Datos"

index .down.> logica
logica .down.> datos
}

file Rest
index .. Rest
database BBDD

Navegador --  Server: "HTTP"
BBDD -up- Server: "HTTP"
